[reframe]
name = "Basic Solidity Smart Contract"
author = "anvie"
min_version = "0.3.4"

[project]
name = "smart-contract-basic"
version = "0.1.0"
ignore_dirs = [
    "target", "build"
]

finish_text = """Usage:

    $ cd $name_kebab_case$

Install prerequisites:

    $ pip install -r requirements.txt

Test:

    $ brownie test

Deploy:

    $ brownie run scripts/deploy.py
"""

[[param]]
description = { ask = "Description ?", default = "My Cool Smart contract" }

[[param]]
author_name = { ask = "Author name?", default="Author" }

[[param]]
author_email = { ask = "Author email?", default="author@example.com" }
